---
nu: "{{ groups.worker | count }}"
idx: "{{ groups.worker.index(inventory_hostname)+1 | int }}"
lnx_name: "{{ 'CentOS' if ansible_distribution == 'CentOS'
               else 'Ubuntu' if ansible_distribution == 'Ubuntu'
               else 'ETC' }}"

nginxdir: "{{ '/usr/share/nginx/html' if ansible_distribution == 'CentOS'
               else '/var/www/html' if ansible_distribution == 'Ubuntu' 
               else 'ETC' }}"

pub_ip: "{{ansible_eth0.ipv4.address}}"

pri_ip: "{{ansible_eht1.ipv4.address}}"
